/* Copyright (c) 2026 tabnas, MIT License */
'use strict'

/* embed-data.js — compile the committed data/ files into a TypeScript
 * module, src/data-bundle.ts, that data.ts imports statically.
 *
 * WHY NOT readFileSync. The data used to be copied to dist/data/ and read
 * from disk at runtime. That works in Node and is a dead end everywhere
 * else: the hosted Worker has no filesystem. Cloudflare's `nodejs_compat`
 * does provide `node:fs`, backed by a virtual root at /bundle — but that
 * root contains only what was statically IMPORTED, so a data file read by
 * path is simply not there:
 *
 *   readFileSync('data/x.json')  =>  no such file or directory '/bundle/data/x.json'
 *   import x from './data/x.json'  =>  works
 *
 * A static import is the one form that resolves in every runtime this
 * package targets, so the data becomes source. The bundler then also gets
 * to see it, which is why there is no longer a dist/data/ copy to keep in
 * sync: one artifact, generated, never hand-edited (ADR-10).
 *
 * The version is embedded here too, for the same reason — packageInfo()
 * used to read ../package.json off disk, which fails identically.
 *
 * So is the rate limit, for a different one. The LIMIT is enforced by the
 * platform from the `ratelimits` binding in wrangler.json; the Worker only
 * has to REPORT it, in /.well-known/mcp and in the 429 body. Retyping 60
 * and 60 into the source would be two numbers that drift silently the
 * first time the binding is tuned — so they are read from wrangler.json,
 * the thing that actually decides. Derive, never hand-maintain.
 *
 * GENERATED, NOT COMMITTED: src/data-bundle.ts is in .gitignore and is
 * rebuilt by `npm run build` before tsc runs. The committed data/ files
 * at the repo root remain the single source; ts/test/data.test.js asserts
 * the embedded copy is byte-identical to them, so a stale bundle fails
 * the suite exactly as a stale dist/data/ copy used to.
 */

const Fs = require('node:fs')
const Path = require('node:path')

const REPO_ROOT = Path.join(__dirname, '..', '..')
const DATA_DIR = Path.join(REPO_ROOT, 'data')
const WRANGLER = Path.join(REPO_ROOT, 'wrangler.json')
const OUT = Path.join(__dirname, '..', 'src', 'data-bundle.ts')

// JSON string escaping is a subset of JS, with one gap: U+2028/U+2029 are
// legal in JSON but were illegal raw in JS string literals before ES2019.
// Escaping them keeps the emitted module safe under any target.
function literal(text) {
  return JSON.stringify(text)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

function build() {
  if (!Fs.existsSync(DATA_DIR)) {
    throw new Error('embed-data: no data/ directory at repo root; ' +
      'run `npm run gen-data` first')
  }

  const pkg = JSON.parse(Fs.readFileSync(
    Path.join(__dirname, '..', 'package.json'), 'utf8'))

  // The binding the platform enforces. Missing means the deploy would
  // have no rate limiting at all, so fail the build rather than emit a
  // module that quietly claims a limit nobody applies.
  const wrangler = JSON.parse(Fs.readFileSync(WRANGLER, 'utf8'))
  const limiter = (wrangler.ratelimits ?? [])
    .find((r) => 'MCP_LIMIT' === r.name)
  if (!limiter?.simple) {
    throw new Error('embed-data: wrangler.json has no MCP_LIMIT ' +
      'ratelimits binding; the hosted endpoint must not deploy unlimited')
  }

  const names = Fs.readdirSync(DATA_DIR).sort()
  const entries = names.map((name) =>
    `  ${literal(name)}: ${literal(
      Fs.readFileSync(Path.join(DATA_DIR, name), 'utf8'))},`)

  return [
    '/* Copyright (c) 2026 tabnas, MIT License */',
    '',
    '/* GENERATED by tools/embed-data.js — DO NOT EDIT, DO NOT COMMIT.',
    ' * Source of truth is data/ at the repo root. Rebuild with',
    ' * `npm run build` (or `node tools/embed-data.js`).',
    ' */',
    '',
    '// This package\'s own identity, for the MCP server handshake.',
    `export const PACKAGE = { name: ${literal(pkg.name)}, ` +
      `version: ${literal(pkg.version)} } as const`,
    '',
    '// The rate limit the MCP_LIMIT binding enforces, from wrangler.json.',
    '// Read, never retyped: the binding decides, this only reports.',
    `export const RATE_LIMIT = { limit: ${Number(limiter.simple.limit)}, ` +
      `period: ${Number(limiter.simple.period)} } as const`,
    '',
    '// Every data/ file, verbatim, keyed by filename. MCP resource reads',
    '// serve these bytes unchanged.',
    'export const FILES: Record<string, string> = {',
    ...entries,
    '}',
    '',
  ].join('\n')
}

module.exports = { build, DATA_DIR, OUT }

if (require.main === module) {
  Fs.writeFileSync(OUT, build())
  console.log('embed-data: wrote ' + Path.relative(REPO_ROOT, OUT))
}
