/* Copyright (c) 2026 tabnas, MIT License */
'use strict'

/* data.test.js — the bundled data/ files are honest.
 *
 * Three gates:
 *
 * 1. STALENESS: regenerate the data IN MEMORY from the sibling checkouts
 *    (tools/gen-data.js buildData) and compare against the committed
 *    files, so a parser schema change or a plugin-manifest change that
 *    forgets `npm run gen-data` fails here instead of shipping stale
 *    copies. Skips gracefully when the parser sibling is absent (a bare
 *    `npx` install has no siblings; CI clones parser and support).
 *
 * 2. PARTIAL FLEETS: CI clones only parser and support, so the plugin
 *    comparison cannot demand all 21 repos. Instead: every manifest that
 *    IS present must match its committed descriptor exactly, and a
 *    present manifest missing from the committed set fails. A committed
 *    descriptor whose repo is not checked out is left alone. With a full
 *    fleet this collapses to exact equality.
 *
 * 3. EMBEDDED COPY: what dist/data.js actually serves — the static
 *    import of src/data-bundle.ts, generated by tools/embed-data.js —
 *    is byte-identical to the committed data/, and covers exactly the
 *    same set of files. This replaces the old dist/data/ byte-compare:
 *    there is no runtime file copy any more, because the Worker has no
 *    filesystem to read one from. The gate is the same in spirit and
 *    stronger in fact, since it tests the bytes a resource read returns
 *    rather than a copy sitting beside the code that returns them.
 */

const { describe, it } = require('node:test')
const assert = require('node:assert')
const Fs = require('node:fs')
const Path = require('node:path')

const { buildData, hasParser, REPO_ROOT, DATA_DIR } =
  require('../tools/gen-data.js')

const data = require('../dist/data.js')

const NAMES = [
  'error-codes.json',
  'grammar.schema.json',
  'diagnostic.schema.json',
  'DIVERGENCE.md',
  'plugins.json',
]

function committed(name) {
  return Fs.readFileSync(Path.join(DATA_DIR, name), 'utf8')
}


describe('data', () => {
  it('committed copies are not stale (regenerate from siblings)', (t) => {
    if (!hasParser()) {
      t.skip('no ../parser sibling checkout: cannot regenerate; ' +
        'run in the fleet layout (or CI, which clones parser) to check ' +
        'staleness')
      return
    }

    const { files } = buildData()

    for (const name of NAMES.filter((n) => 'plugins.json' !== n)) {
      assert.strictEqual(committed(name), files[name],
        `data/${name} is stale: run npm run gen-data (from ts/) and ` +
        'commit the result')
    }

    const regenerated = JSON.parse(files['plugins.json'])
    const bundled = JSON.parse(committed('plugins.json'))
    assert.strictEqual(bundled.generated_from, 'sibling checkouts')

    const bundledByName = new Map(bundled.plugins.map((p) => [p.name, p]))
    for (const p of regenerated.plugins) {
      assert.ok(bundledByName.has(p.name),
        `plugin ${p.name} has a manifest in the fleet but is not in ` +
        'data/plugins.json: run npm run gen-data and commit')
      assert.deepStrictEqual(bundledByName.get(p.name), p,
        `data/plugins.json entry for ${p.name} is stale: run ` +
        'npm run gen-data and commit')
    }

    // Committed descriptors whose repos are absent are fine (partial
    // fleet); with a full fleet the two sets are equal.
    if (regenerated.plugins.length === bundled.plugins.length) {
      assert.deepStrictEqual(bundled, regenerated)
    }
  })

  it('descriptors are sorted by name and carry a name', () => {
    const bundled = JSON.parse(committed('plugins.json'))
    const names = bundled.plugins.map((p) => p.name)
    assert.ok(0 < names.length, 'no bundled plugin descriptors')
    assert.deepStrictEqual(names, [...names].sort())
    assert.strictEqual(new Set(names).size, names.length,
      'duplicate plugin names')
  })

  it('regeneration is deterministic (build twice, compare)', (t) => {
    if (!hasParser()) {
      t.skip('no ../parser sibling checkout')
      return
    }
    assert.deepStrictEqual(buildData().files, buildData().files)
  })

  it('the embedded bundle is byte-identical to the committed data/', () => {
    // data.js serves these bytes verbatim for every MCP resource read,
    // so a stale bundle would quietly answer with old schemas. The
    // generated module is not committed; this is what keeps it honest.
    for (const name of NAMES) {
      assert.strictEqual(data.rawData(name), committed(name),
        `embedded ${name} differs from data/${name}: run npm run build`)
    }
  })

  it('the embedded set is exactly the committed data/ directory', () => {
    // Derived on both sides — no hand-kept list to drift. A new data/
    // file that embed-data picked up but NAMES does not know about is
    // caught here rather than shipping unnoticed.
    assert.deepStrictEqual(
      data.dataNames(), Fs.readdirSync(DATA_DIR).sort())
    assert.deepStrictEqual(data.dataNames(), [...NAMES].sort())
  })

  it('loaders parse and expose the expected shapes', () => {
    assert.strictEqual(typeof data.errorRegistry().codes.unexpected.message,
      'string')
    assert.strictEqual(data.grammarSchema().$id,
      'https://tabnas.dev/schema/grammar.schema.json')
    assert.strictEqual(data.diagnosticSchema().$id,
      'https://tabnas.dev/schema/diagnostic.schema.json')
    assert.ok(Array.isArray(data.pluginIndex().plugins))
    assert.ok(data.divergence().startsWith('# Divergences'))
    assert.strictEqual(data.packageInfo().name, '@tabnas/mcp')
    // Embedded at build time; it must track package.json, not lag it.
    assert.strictEqual(data.packageInfo().version,
      require('../package.json').version)
  })

  it('repo layout: data/ lives at the repo root', () => {
    assert.strictEqual(Path.resolve(DATA_DIR),
      Path.resolve(Path.join(REPO_ROOT, 'data')))
  })
})
